name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          cache: true

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run CTest
        run: ctest --test-dir build --output-on-failure --build-config Release

      - name: Run MVP
        run: ./build/bin/eon-orchestrator ./build/Plugins ./Workflows/minimal.workflow.json
